<?php 
/**
 * @file
 * Main Jarvis class
 */

/**
 * Jarvis Class
 */
class Jarvis {

  private $init = FALSE;
  public $hotkey;
  public $ajax_search;

  /**
   * Singleton instance
   */
  private static $instance = FALSE;

  /**
   * Singleton
   */
  public static function instance() {
    if (!self::$instance) {
      self::$instance = new self();
    }
    return self::$instance;
  }

  /**
   * Init Jarvis
   */
  public function init() {
    if ( $this->init ) return;
    $this->init = TRUE;

    // Hotkey is '/'
    $this->hotkey = 191;
    // Ajax search endpoint
    $this->ajax_search = 'jarvis/autocomplete';
  }

  /**
   * Localize Javascript
   * @return string to be embedded with JS
   */
  public function localize() {
    $jarvis = array(
      'hotkey' => $this->hotkey,
      'ajax_search' => url($this->ajax_search),
      'menu_items' => $this->menu_items(),
    );

   return 'var jarvis = ' . json_encode($jarvis) . ';'; //, JSON_PRETTY_PRINT
  }

  /**
   * Perform a search
   * Echos search results to prevent the Drupal templates from being output
   */
  public function search() {
    $q = isset($_REQUEST['q']) ? trim($_REQUEST['q']) : '';

    $response = array(
      'results' => array()
    );

    if ( strlen($q) ) {
      // Split words on whitespace
      $q_words = preg_split('/\s+/', $q, NULL, PREG_SPLIT_NO_EMPTY);

      $results = array_merge($this->node_search($q, $q_words), $this->term_search($q, $q_words));
      usort($results, function ($a, $b) {
        if ($a['jarvis_sort'] == $b['jarvis_sort']) {
          if (strlen($a['title']) == strlen($b['title'])) return 0;
          return strlen($a['title']) < strlen($b['title']) ? -1 : 1;
        }
        return $a['jarvis_sort'] > $b['jarvis_sort'] ? -1 : 1;
      });
      $response['results'] = $results;

      // DEBUGGING
      $response['q'] = $q;
      $response['q_words'] = $q_words;

    }

    echo json_encode($response);
  }

  protected function node_search($q, $q_words) {
    // Sort by relevance of search phrase related to title.
    $relevance = "0 \n";
    foreach ($q_words as $i => $q_word) {
      // Keyword matches
      $relevance .= "+ if(n.title REGEXP :q{$i}_full, 1, 0) \n";
      $relevance .= "+ if(n.title REGEXP :q{$i}_start, 1, 0) \n";
    }
    $relevance .= " as 'jarvis_sort' \n";

    // Search for matching titles or nid
    $where = "";
    // Only need to search nid if a single word
    if (count($q_words) === 1) {
      $where .= "n.nid = :q OR \n";
    }
    $where .= "(";
    foreach ($q_words as $i => $q_word) {
      $where .= "n.title REGEXP :q{$i}_contain AND ";
    }
    $where .= "1 = 1) \n";

    // Query parameters
    $params = array();
    if (count($q_words) === 1) {
      $params[':q'] = $q;
    }
    foreach ($q_words as $i => $q_word) {
      $q_word_escaped = preg_quote($q_word);
      $params[':q' . $i . '_full'] = '[[:<:]]' . $q_word_escaped . '[[:>:]]';
      $params[':q' . $i . '_start'] = '[[:<:]]' . $q_word_escaped;
      $params[':q' . $i . '_contain'] = $q_word_escaped;
    }

    $query = "SELECT DISTINCT \n" . 
              "  n.nid AS 'id', \n" . 
              "  n.type AS 'type', \n" . 
              "  n.title AS 'title', \n" . 
              $relevance .
              "FROM \n" . 
              "  {node} n \n" . 
              "WHERE \n" .
              $where . 
              "ORDER BY \n" .
              "  jarvis_sort DESC, \n" . // Jarvis match best to worst
              "  LENGTH(LOWER(n.title)), \n" . // Title length shortest to longest
              "  n.changed DESC \n" . // Updated most recently to oldest
              "LIMIT 20";

    // @see https://api.drupal.org/api/drupal/includes!database!database.inc/function/db_query/7
    $result = db_query($query, $params);

    $results = $result->fetchAll();

    $response = array();
    foreach ($results as $index => $item) {
      $id = $item->id;

      $item = (array) $item;
      $item['edit_url'] = url('node/' . $id . '/edit');
      
      $response[] = $item;
    }

    return $response;
  }

  protected function term_search($q, $q_words) {
    // Sort by relevance of search phrase related to title.
    $relevance = "0 \n";
    foreach ($q_words as $i => $q_word) {
      // Keyword matches
      $relevance .= "+ if(t.name REGEXP :q{$i}_full, 1, 0) \n";
      $relevance .= "+ if(t.name REGEXP :q{$i}_start, 1, 0) \n";
    }
    $relevance .= " as 'jarvis_sort' \n";

    // Search for matching term names
    $where = "(";
    foreach ($q_words as $i => $q_word) {
      $where .= "t.name REGEXP :q{$i}_contain AND ";
    }
    $where .= "1 = 1) \n";

    // Query parameters
    $params = array();
    foreach ($q_words as $i => $q_word) {
      $q_word_escaped = preg_quote($q_word);
      $params[':q' . $i . '_full'] = '[[:<:]]' . $q_word_escaped . '[[:>:]]';
      $params[':q' . $i . '_start'] = '[[:<:]]' . $q_word_escaped;
      $params[':q' . $i . '_contain'] = $q_word_escaped;
    }

    $query = "SELECT DISTINCT \n" . 
              "  t.tid AS 'id', \n" . 
              "  v.name AS 'type', \n" . 
              "  t.name AS 'title', \n" . 
              $relevance .
              "FROM \n" . 
              "  {taxonomy_term_data} t \n" . 
              "  LEFT JOIN {taxonomy_vocabulary} v ON t.vid = v.vid \n" . 
              "WHERE \n" .
              $where . 
              "ORDER BY \n" .
              "  jarvis_sort DESC, \n" . // Jarvis match best to worst
              "  LENGTH(LOWER(t.name)) \n" . // Title length shortest to longest
              "LIMIT 20";

    // @see https://api.drupal.org/api/drupal/includes!database!database.inc/function/db_query/7
    $result = db_query($query, $params);

    $results = $result->fetchAll();

    $response = array();
    foreach ($results as $index => $item) {
      $item->type .= ' Term';
      $id = $item->id;

      $item = (array) $item;
      $item['edit_url'] = url('taxonomy/term/' . $id . '/edit');
      
      $response[] = $item;
    }

    return $response;
  }

  /**
   * Parse through menus to get menu_items
   * @return array
   */
  public function menu_items() {
    $menu_items = array();
    $menus = array('management', 'user-menu');
    $data = array();
    $tree = array();

    // Allows modules to add additional menus
    drupal_alter('jarvis_menus', $menus);

    // Get all menu items
    foreach ($menus as $menu) {
      $data = menu_tree_all_data($menu);
      foreach ($data as $tree) {
        $menu_items = array_merge(
          $menu_items, 
          $this->_menu_items($tree['below'])
        );
      }
    }

    // Merge together with additional menu items
    $menu_items = array_merge($menu_items, $this->_additional_menu_items());

    // Allow modules to alter final menu items
    drupal_alter('jarvis_menu_items', $menu_items);
    
    return $menu_items;
  }

  /**
   * Internal function to parse through menu trees
   * @param array $tree
   * @return array
   */
  public function _menu_items($tree, $parent = NULL) {
    static $id = 0;
    // Prevent runaway menus
    if ( $id++ > 1000 ) return array();

    $menu_items = array();

    foreach ($tree as $menu_item) {
      // Skip inaccessible, invisible links, or links that point their parent.
      if (!$menu_item['link']['access'] 
        || ($menu_item['link']['type'] & MENU_LINKS_TO_PARENT)
        || $menu_item['link']['hidden'] == 1) {
        continue;
      }

      $menu_item_parent = $parent;

      if (!empty($menu_item['link']['link_path'])) {
        $menu_item_parent .= $menu_item['link']['link_title'] . ' » ';
        $menu_items[] = array(
          'type' => 'Menu Item',
          'title' => $parent . $menu_item['link']['link_title'],
          'edit_url' => url($menu_item['link']['link_path'])
        );
      }
      if (!empty($menu_item['below'])) {
        $menu_items = array_merge(
            $menu_items, 
            $this->_menu_items($menu_item['below'], $menu_item_parent)
        );
      }
    }

    return $menu_items;
  }

  public function _additional_menu_items() {
    $menu_items = array();

    // Content Types
    if (user_access('administer content types')) {
      foreach (node_type_get_types() as $node_type => $node) {
        $menu_items[] = array(
          'type' => 'Content Type',
          'title' => 'Structure » Content Types » ' . $node->name,
          'edit_url' => url('admin/structure/types/manage/' . $node_type)
        );
      }
    }
    foreach (node_type_get_types() as $node_type => $node) {
      if (user_access('bypass node access') || user_access('create ' . $node_type . ' content')) {
        $node_type = str_replace('_', '-', $node_type);
        $menu_items[] = array(
          'type' => 'Content',
          'title' => 'Content » Add Content » ' . $node->name,
          'edit_url' => url('node/add/' . $node_type)
        );
      }
    }

    // Taxonomies
    if (user_access('administer taxonomy')) {
      foreach (taxonomy_vocabulary_get_names() as $name => $taxonomy) {
        $menu_items[] = array(
          'type' => 'Taxonomy',
          'title' => 'Structure » Taxonomy » ' . $taxonomy->name,
          'edit_url' => url('admin/structure/taxonomy/' . $name)
        );
      }
    }

    // Nodequeues
    if (module_exists('nodequeue') && user_access('administer nodequeue')) {
      foreach (nodequeue_load_subqueues(nodequeue_get_all_qids()) as $subqueue) {
        $menu_items[] = array(
          'type' => 'Nodequeue',
          'title' => 'Structure » Nodequeues » ' . $subqueue->title,
          'edit_url' => url('admin/structure/nodequeue/' . $subqueue->qid . '/view/' . $subqueue->sqid)
        );
      }
    }

    // Views
    if (module_exists('views') && user_access('administer views')) {
      foreach (views_get_enabled_views() as $name => $view) {
        $menu_items[] = array(
          'type' => 'View',
          'title' => 'Structure » Views » ' . ( $view->human_name ? $view->human_name : $name ),
          'edit_url' => url('admin/structure/views/view/' . $name)
        );
      }
    }

    // Context
    if (module_exists('context') && user_access('administer contexts')) {
      foreach (context_enabled_contexts() as $name => $context) {
        $menu_items[] = array(
          'type' => 'Context',
          'title' => 'Structure » Context » ' . ($context->tag ? $context->tag . ' » ' : '') . $name,
          'edit_url' => url('admin/structure/context/list/' . $name . '/edit')
        );
      }
    }

    return $menu_items;
  }

}

/**
 * Init hook
 */
function jarvis_init() {
  if (!user_is_logged_in() || !user_access('use jarvis')) 
    return;

  Jarvis::instance()->init();

  // Load Jarvis javascript
  drupal_add_js(drupal_get_path('module', 'jarvis') . '/js/jquery-ui-1.10.2.custom.js');
  drupal_add_js(Jarvis::instance()->localize(), 'inline');
  drupal_add_js(drupal_get_path('module', 'jarvis') . '/js/jarvis.js');

  // Load Jarvis CSS
  drupal_add_css(drupal_get_path('module', 'jarvis') . '/css/jquery-ui-1.10.2.custom.css');
  drupal_add_css(drupal_get_path('module', 'jarvis') . '/css/jarvis.css');
}

/**
 * Perm hook
 */
function jarvis_permission() {
  $items = array();

  $items['use jarvis'] = array(
    'title' => 'Use Jarvis Search',
    'description' => 'Enable Jarvis menu and content search with the "/" hotkey.'
  );

  return $items;
}

/**
 * Menu hook
 */
function jarvis_menu() {
  Jarvis::instance()->init();

  $items = array();
  // Jarvis node search
  $items[Jarvis::instance()->ajax_search] = array(
    'page callback' => '_jarvis_search',
    'access arguments' => array('use jarvis'),
    'type' => MENU_CALLBACK
  );
  
  return $items;
}

/**
 * Internal Jarvis Search
 */
function _jarvis_search() {
  return Jarvis::instance()->search();
}